def get_instrucciones():
    instrucciones = ""
    # LDAA(IMM)
    instrucciones += instruction_to_string_eha(direccion="860",prueba="00",vf="0",mutations=["nepc2","ncbd"])
    instrucciones += instruction_to_string_eha(direccion="861",prueba="00",vf="0",mutations=["nas","pc0","nwa","ea0"])
    instrucciones += instruction_to_string_eha(direccion="862",prueba="0f",vf="1",inst="11",mutations=["cz","cn","cv","b3","b6","b2"])
    instrucciones += instruction_to_string_eha(direccion="863",liga="09",prueba="18",vf="0",inst="01",mutations=["nepc2","ncbd"])
    # LDAB(DIR)
    instrucciones += instruction_to_string_eha(direccion="D60",prueba="00",vf="0",mutations=["nepc2","ncbd"])
    instrucciones += instruction_to_string_eha(direccion="D61",prueba="00",vf="0",mutations=["nera0","ra0","ra1","pc0","nas"])
    instrucciones += instruction_to_string_eha(direccion="D62",prueba="00",vf="0",mutations=["nera2","ncbd"])
    instrucciones += instruction_to_string_eha(direccion="D63",prueba="00",vf="0",mutations=["nas","nwb","eb0"])
    instrucciones += instruction_to_string_eha(direccion="D64",prueba="0f",vf="1",inst="11" ,mutations=["cz","cn","cv","b4","b7","b2"])
    instrucciones += instruction_to_string_eha(direccion="D65",liga="09",prueba="18",vf="0",inst="01" ,mutations=["nepc2","ncbd"])
    # LDAB(IMM)
    instrucciones += instruction_to_string_eha(direccion="C60",prueba="00",vf="0",mutations=["nepc2","ncbd"])
    instrucciones += instruction_to_string_eha(direccion="C61",prueba="00",vf="0",mutations=["nas","pc0","nwa","ea0"])
    instrucciones += instruction_to_string_eha(direccion="C62",prueba="0f",vf="1",inst="11",mutations=["cz","cn","cv","b4","b7","b2"])
    instrucciones += instruction_to_string_eha(direccion="C63",liga="09",prueba="18",vf="0",inst="01",mutations=["nepc2","ncbd"])
    # LDAA(DIR)
    instrucciones += instruction_to_string_eha(direccion="960",prueba="00",vf="0",mutations=["nepc2","ncbd"])
    instrucciones += instruction_to_string_eha(direccion="961",prueba="00",vf="0",mutations=["nera0","ra0","ra1","pc0","nas"])
    instrucciones += instruction_to_string_eha(direccion="962",prueba="00",vf="0",mutations=["nera2","ncbd"])
    instrucciones += instruction_to_string_eha(direccion="963",prueba="00",vf="0",mutations=["nas","nwa","ea0"])
    instrucciones += instruction_to_string_eha(direccion="964",prueba="0f",vf="1",inst="11" ,mutations=["cz","cn","cv","b5","b6","b2"])
    instrucciones += instruction_to_string_eha(direccion="965",liga="09",prueba="18",vf="0",inst="01" ,mutations=["nepc2","ncbd"])
    # JMP(EXT)
    instrucciones += instruction_to_string_eha(direccion="7E0",prueba="00",vf="0",mutations=["nepc2","ncbd"])
    instrucciones += instruction_to_string_eha(direccion="7E1",prueba="00",vf="0",mutations=["nas","bd","nera1","ra2","pc0"])
    instrucciones += instruction_to_string_eha(direccion="7E2",prueba="00",vf="0",mutations=["nepc2","ncbd"])
    instrucciones += instruction_to_string_eha(direccion="7E3",prueba="00",vf="0",mutations=["nas","nera0","ra0","ra1","pc0"])
    instrucciones += instruction_to_string_eha(direccion="7E4",prueba="0f",vf="1",inst="11" ,mutations=["pc2","pc0","nepc1","nepc0","nera1","nera0"])
    instrucciones += instruction_to_string_eha(direccion="7E5",liga="09",prueba="18",vf="0",inst="01" ,mutations=["nepc2","ncbd"])
    # ABA(INH)
    instrucciones += instruction_to_string_eha(direccion="1B0",prueba="00",vf="0",mutations=["ea1","ea0","eb1","eb0","upa0","selmux","upa7"])
    instrucciones += instruction_to_string_eha(direccion="1B1",prueba="0f",vf="1",inst="11" ,mutations=["noeupa","ndupa","ea0","nwa","cn","cz","cv","cc"])
    instrucciones += instruction_to_string_eha(direccion="1B2",liga="09",prueba="18",vf="0",inst="01" ,mutations=["nepc2","ncbd"])
    # BRA
    instrucciones += instruction_to_string_eha(direccion="200",prueba="00",vf="0",mutations=["nhb","nera0","ra1","ra0","nepc2","ncbd"])
    instrucciones += instruction_to_string_eha(direccion="201",prueba="00",vf="0",mutations=["pc0","nas","upa2","upa1","upa0","upa5","upa4"])
    instrucciones += instruction_to_string_eha(direccion="202",prueba="00",vf="0",mutations=["nepc0","upa2","upa1","selmux","upa7"])
    instrucciones += instruction_to_string_eha(direccion="203",prueba="00",vf="1",inst="01", liga="205",mutations=["noeupa","ndupa","nepc0","pc1","pc0","cc"])
    instrucciones += instruction_to_string_eha(direccion="204",prueba="18",vf="0",inst="01", liga="206",mutations=["nepc1","selbus","upa2","upa1","upa0"])
    instrucciones += instruction_to_string_eha(direccion="205",prueba="00",vf="0",mutations=["nepc1","selbus","upa2","upa1","upa0","upa5"])
    instrucciones += instruction_to_string_eha(direccion="206",prueba="00",vf="0",mutations=["nepc1","noeupa","ndupa","pc2"])
    instrucciones += instruction_to_string_eha(direccion="207",prueba="0f",vf="1",inst="11" ,mutations=["nera0","cc","b0"])
    instrucciones += instruction_to_string_eha(direccion="208",liga="09",prueba="18",vf="0",inst="01" ,mutations=["nepc2","ncbd"])
    #BNE
    instrucciones += instruction_to_string_eha(direccion="260",prueba="12",vf="0",inst="01", liga="201",mutations=['nHB','nERA0','RA1','RA0','nEPC2','nCBD'])
    instrucciones += instruction_to_string_eha(direccion="261",prueba="0f",vf="1",inst="11" ,mutations=["pc0"])
    instrucciones += instruction_to_string_eha(direccion="262",liga="09",prueba="18",vf="0",inst="01" ,mutations=["nepc2","ncbd"])
    #XABA
    instrucciones += instruction_to_string_eha(direccion="AD0",prueba="09",vf="0",inst="01", liga="201",mutations=['EA1','EA0','EB1','EB0','UPA0','Selmux','UPA7'])
    instrucciones += instruction_to_string_eha(direccion="AD1",prueba="0f",vf="1",inst="11" ,mutations=['nOEUPA','nDUPA','nEX0','X1','X0','PC0','CN','CZ','CV','CC'])
    instrucciones += instruction_to_string_eha(direccion="AD2",liga="09",prueba="18",vf="0",inst="01" ,mutations=["nepc2","ncbd"])
    #BEQ
    instrucciones += instruction_to_string_eha(direccion="270",prueba="12",vf="1",inst="01", liga="201",mutations=['nHB','nERA0','RA1','RA0','nEPC2','nCBD'])
    instrucciones += instruction_to_string_eha(direccion="271",prueba="0f",vf="1",inst="11" ,mutations=["pc0"])
    instrucciones += instruction_to_string_eha(direccion="272",liga="09",prueba="18",vf="0",inst="01" ,mutations=["nepc2","ncbd"])
    #BLE
    instrucciones += instruction_to_string_eha(direccion="2F0",prueba="12",vf="1",inst="01", liga="201",mutations=['nHB','nERA0','RA1','RA0','nEPC2','nCBD'])
    instrucciones += instruction_to_string_eha(direccion="2F1",prueba="13",vf="1",inst="01", liga="2F5",mutations=[])
    instrucciones += instruction_to_string_eha(direccion="2F2",prueba="11",vf="1",inst="01", liga="201",mutations=[])
    instrucciones += instruction_to_string_eha(direccion="2F3",vf="1",inst="11",mutations=['pc0'])
    instrucciones += instruction_to_string_eha(direccion="2F4",liga="09",prueba="18",vf="0",inst="01" ,mutations=["nepc2","ncbd"])
    instrucciones += instruction_to_string_eha(direccion="2F5",prueba="11",vf="0",inst="01", liga="201",mutations=[])
    #STAB
    instrucciones += instruction_to_string_eha(direccion="d70",prueba="00",vf="0",mutations=["EB1","EB0","UPA0","UPA1","UPA6"])
    instrucciones += instruction_to_string_eha(direccion="d71",prueba="00",vf="0",mutations=['nOEUPA','nDUPA','nERA1','RA2'])
    instrucciones += instruction_to_string_eha(direccion="d72",prueba="00",vf="0",mutations=['nEPC2','nCBD'])
    instrucciones += instruction_to_string_eha(direccion="d73",prueba="00",vf="0",mutations=['RA1','RA0','PC0','nAS','nERA0'])
    instrucciones += instruction_to_string_eha(direccion="d74",prueba="00",vf="0",mutations=['nERA2','nCBD'])
    instrucciones += instruction_to_string_eha(direccion="d75",prueba="00",vf="0",mutations=['EB0','nAS','nRW'])
    instrucciones += instruction_to_string_eha(direccion="d76",vf="1",inst="11",mutations=['B7','B4','B2','CN','CV','cZ'])
    instrucciones += instruction_to_string_eha(direccion="d77",liga="09",prueba="18",vf="0",inst="01" ,mutations=["nepc2","ncbd"])
    #STAA
    instrucciones += instruction_to_string_eha(direccion="970",prueba="00",vf="0",mutations=["nEPC2",'nCBD'])
    instrucciones += instruction_to_string_eha(direccion="971",prueba="00",vf="0",mutations=['nERA0','nAS','nRW'])
    instrucciones += instruction_to_string_eha(direccion="972",prueba="00",vf="0",mutations=['nAS','PC0'])
    instrucciones += instruction_to_string_eha(direccion="973",vf="1",inst="11",mutations=['B2','B3','B6','CN','CV','cZ'])
    instrucciones += instruction_to_string_eha(direccion="974",liga="09",prueba="18",vf="0",inst="01" ,mutations=["nepc2","ncbd"])
    #ADDA
    instrucciones += instruction_to_string_eha(direccion="db0",prueba="00",vf="0",mutations=['nEPC2','nCBD'])
    instrucciones += instruction_to_string_eha(direccion="db1",prueba="00",vf="0",mutations=['RA1','RA0','PC0','nAS','nERA0'])
    instrucciones += instruction_to_string_eha(direccion="db2",prueba="00",vf="0",mutations=['nERA2','nCBD'])
    instrucciones += instruction_to_string_eha(direccion="db3",prueba="00",vf="0",mutations=['nAS','EA1','EA0','UPA7','UPA2','UPA0','SELMUX','ACCSEC'])
    instrucciones += instruction_to_string_eha(direccion="db4",vf="1",inst="11",mutations=['NOEUPA','NDUPA','NWA','EA0','CN','CZ','CV','CC'])
    instrucciones += instruction_to_string_eha(direccion="db5",liga="09",prueba="18",vf="0",inst="01" ,mutations=["nepc2","ncbd"])
    #LDX(IMM)
    instrucciones += instruction_to_string_eha(direccion="CE0",prueba="00",vf="0",mutations=['nEPC2','nCBD'])
    instrucciones += instruction_to_string_eha(direccion="CE1",prueba="00",vf="0",mutations=['nAS','PC0','X0','X1','nEX0'])
    instrucciones += instruction_to_string_eha(direccion="CE2",vf="1",inst="11",mutations=['CZ','CN','CV','B4','B3','B6','B7','B2'])
    instrucciones += instruction_to_string_eha(direccion="CE3",liga="09",prueba="18",vf="0",inst="01" ,mutations=["nepc2","ncbd"])
    #ADDA(ind,x)
    instrucciones += instruction_to_string_eha(direccion="ab0",prueba="00",vf="0",mutations=['nEPC2','nCBD'])
    instrucciones += instruction_to_string_eha(direccion="ab1",prueba="00",vf="0",mutations=['nAS','PC0','UPA2','UPA1','UPA0','UPA5','UPA4'])
    instrucciones += instruction_to_string_eha(direccion="ab2",prueba="00",vf="0",mutations=['nEX0','UPA2','UPA1','SELMUX','UPA7'])
    instrucciones += instruction_to_string_eha(direccion="ab3",prueba="00",vf="0",mutations=['nERA0','nOEUPA','nDUPA','RA2','CC'])
    instrucciones += instruction_to_string_eha(direccion="ab4",prueba="00",vf="0",mutations=['nEX1','SELBUS','UPA2','UPA1','UPA0'])
    instrucciones += instruction_to_string_eha(direccion="ab5",prueba="00",vf="0",mutations=['nOEUPA','nDUPA','nERA1','RA1','RA0'])
    instrucciones += instruction_to_string_eha(direccion="ab6",prueba="00",vf="0",mutations=['nERA2','nCBD'])
    instrucciones += instruction_to_string_eha(direccion="ab7",prueba="00",vf="0",mutations=['nAS','EA1','EA0','UPA2','UPA0','SELMUX'])
    instrucciones += instruction_to_string_eha(direccion="ab8",vf="1",inst="11",mutations=['nOEUPA','nDUPA','EA0','nWA','CH','CN','CZ','CV','CC'])
    instrucciones += instruction_to_string_eha(direccion="ab9",liga="09",prueba="18",vf="0",inst="01" ,mutations=["nepc2","ncbd"])
    #SUBB(ind,x)
    instrucciones += instruction_to_string_eha(direccion="e00",prueba="00",vf="0",mutations=['nEPC2','nCBD'])
    instrucciones += instruction_to_string_eha(direccion="e01",prueba="00",vf="0",mutations=['nAS','PC0','UPA2','UPA1','UPA0','UPA5','UPA4'])
    instrucciones += instruction_to_string_eha(direccion="e02",prueba="00",vf="0",mutations=['nEX0','UPA2','UPA1','SELMUX','UPA7'])
    instrucciones += instruction_to_string_eha(direccion="e03",prueba="00",vf="0",mutations=['nERA0','nOEUPA','nDUPA','RA2','CC'])
    instrucciones += instruction_to_string_eha(direccion="e04",prueba="00",vf="0",mutations=['nEX1','SELBUS','UPA2','UPA1','UPA0'])
    instrucciones += instruction_to_string_eha(direccion="e05",prueba="00",vf="0",mutations=['nOEUPA','nDUPA','nERA1','RA1','RA0'])
    instrucciones += instruction_to_string_eha(direccion="e06",prueba="00",vf="0",mutations=['nERA2','nCBD'])
    instrucciones += instruction_to_string_eha(direccion="e07",prueba="00",vf="0",mutations=['nAS','EB1','EB0','UPA3','UPA4','SELMUX'])
    instrucciones += instruction_to_string_eha(direccion="e08",vf="1",inst="11",mutations=['nOEUPA','nDUPA','EB0','nWB','CH','CN','CZ','CV','CC'])
    instrucciones += instruction_to_string_eha(direccion="e09",liga="09",prueba="18",vf="0",inst="01" ,mutations=["nepc2","ncbd"])
    #CPX(imm)
    instrucciones += instruction_to_string_eha(direccion="8C0",prueba="00",vf="0",mutations=['nEPC2','nCBD'])
    instrucciones += instruction_to_string_eha(direccion="8C1",prueba="00",vf="0",mutations=['nAS','PC0','RA2','nERA1','BD'])
    instrucciones += instruction_to_string_eha(direccion="8C2",prueba="00",vf="0",mutations=['nEPC2','nCBD'])
    instrucciones += instruction_to_string_eha(direccion="8C3",prueba="00",vf="0",mutations=['nAS','PC0','RA1','RA0','nERA0'])
    instrucciones += instruction_to_string_eha(direccion="8C4",prueba="00",vf="0",mutations=['UPA2','UPA1','UPA0','UPA5','UPA4','nERA0'])
    instrucciones += instruction_to_string_eha(direccion="8C5",prueba="00",vf="0",mutations=['nEX0','UPA2','UPA1','UPA4','SELMUX','CN','CZ','CV','CC'])
    instrucciones += instruction_to_string_eha(direccion="8C6",prueba="00",vf="0",mutations=['nERA0','RA1','RA0','nDUPA','nOEUPA'])
    instrucciones += instruction_to_string_eha(direccion="8C7",prueba="00",vf="0",mutations=['UPA2','UPA1','UPA0','UPA5','UPA4','nERA1'])
    instrucciones += instruction_to_string_eha(direccion="8C8",prueba="00",vf="0",mutations=['nEX1','UPA2','UPA1','UPA4'])
    instrucciones += instruction_to_string_eha(direccion="8C9",vf="1",inst="11",mutations=['nOEUPA','nDUPA','nERA1','RA2','CH','CN','CZ','CV','CC'])
    instrucciones += instruction_to_string_eha(direccion="8CA",liga="09",prueba="18",vf="0",inst="01" ,mutations=["nepc2","ncbd"])
    #XPAR(INH)
    instrucciones += instruction_to_string_eha(direccion="A50",prueba="00",vf="0",mutations=['nEPC2','nCBD','nERA2'])
    instrucciones += instruction_to_string_eha(direccion="A51",vf="1",inst="11",mutations=['nAS','nERA0','RA0','RA1'])
    instrucciones += instruction_to_string_eha(direccion="A52",prueba="0f",vf="1",inst="11",mutations=['nHB','CC','B0'])
    instrucciones += instruction_to_string_eha(direccion="A53",liga="09",prueba="18",vf="0",inst="01" ,mutations=["nepc2","ncbd"])
    #INX
    instrucciones += instruction_to_string_eha(direccion="080",prueba="00",vf="0",mutations=['X0'])
    instrucciones += instruction_to_string_eha(direccion="081",vf="1",inst="11",mutations=['CZ','B4','B3'])
    instrucciones += instruction_to_string_eha(direccion="082",liga="09",prueba="18",vf="0",inst="01" ,mutations=["nepc2","ncbd"])